name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  update-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Pull latest images
        run: |
          docker pull meowen0228/civil:latest
          docker stop web
          docker rm web
          docker run --name web -p 8080:8080 -d meowen0228/civil:latest
          docker image prune -f
