name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the frontend and copy to backend's public folder
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          cp -r dist/* ../backend/public/
          rm -rf dist
      
      # Build the backend
      - name: Build Backend
        run: |
          cd backend
          npm install
          npx tsc
          
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_ALL }}
          
      # Build the Docker image and push to Docker Hub
      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/civil:latest
